// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATc5Y179FjD0onPKehGqPhejMJNa64Etk',
    appId: '1:427513836150:web:ac755c97ca625d5e176557',
    messagingSenderId: '427513836150',
    projectId: 'eldercare-app-442bf',
    authDomain: 'eldercare-app-442bf.firebaseapp.com',
    storageBucket: 'eldercare-app-442bf.firebasestorage.app',
    measurementId: 'G-0JBLTTRVD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeMQclvIcZTaNDkX2Q0Jv7F-1zmpWvKg8',
    appId: '1:427513836150:android:02970b92e26a5430176557',
    messagingSenderId: '427513836150',
    projectId: 'eldercare-app-442bf',
    storageBucket: 'eldercare-app-442bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX5gAfoLqOrcNan0O881OomPOej8OUjgs',
    appId: '1:427513836150:ios:ca607588899fca56176557',
    messagingSenderId: '427513836150',
    projectId: 'eldercare-app-442bf',
    storageBucket: 'eldercare-app-442bf.firebasestorage.app',
    iosBundleId: 'com.example.mobileCaregivingAndMonitoringSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX5gAfoLqOrcNan0O881OomPOej8OUjgs',
    appId: '1:427513836150:ios:ca607588899fca56176557',
    messagingSenderId: '427513836150',
    projectId: 'eldercare-app-442bf',
    storageBucket: 'eldercare-app-442bf.firebasestorage.app',
    iosBundleId: 'com.example.mobileCaregivingAndMonitoringSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATc5Y179FjD0onPKehGqPhejMJNa64Etk',
    appId: '1:427513836150:web:5ab1ff8ed5d7b249176557',
    messagingSenderId: '427513836150',
    projectId: 'eldercare-app-442bf',
    authDomain: 'eldercare-app-442bf.firebaseapp.com',
    storageBucket: 'eldercare-app-442bf.firebasestorage.app',
    measurementId: 'G-3ZDTXXT0JH',
  );
}
